### ISSUE TITLE
How to work for iOS build

### ISSUE THREAD

**Issue by takaken1994** [marksatt/DistCode#10]
Hi.

I installed DistCode 3.03 and use xcode7.3.
I selected iphone SDK on DistCode GUI and builded iOS project.
But maybe, compiler mode is mac. Building was failed.

Does it support iOS project?

Best Regards.

**Comment by marksatt** [comment]
Err, no. In Xcode you have to go to the iOS target's build setting and select the distcc compiler to compile with. The drop-downs in DistCode are just a convenience to show which SDKs are installed - it doesn't control anything in Xcode.
