### ISSUE TITLE
Not able to offload task to Host

### ISSUE THREAD

**Issue by kaustubhkabra** [marksatt/DistCode#11]
<img width="1440" alt="screen shot 2016-10-05 at 12 39 17 pm" src="https://cloud.githubusercontent.com/assets/642690/19115122/606ea0a8-8b2e-11e6-949e-4ba3e0384fc0.png">
I am able to see 2 hosts but no offloading happens, at least nothing gets printed in verbose. I have made sure that distcc is the compiler selected in Xcode build settings for the project. Can someone please comment ?
Xcode - 8
Swift - 2.3
Distcc - 3.2

**Comment by marksatt** [comment]
Only C/C++/Objective-C/Objective-C++ will be distributed as distcc is a GCC/clang compiler wrapper - it won't understand the Swift compiler arguments properly and will fallback to running it locally. 

The other issue covers the case where it isn't distributing C compile jobs...
