### ISSUE TITLE
Failed to build distcc on osx 10.12.3

### ISSUE THREAD

**Issue by S1GSEGV** [marksatt/DistCode#13]
checking for expandargv in -liberty... no
configure: error: Cannot find libiberty
Command ./configure failed with exit code 1

How can I fix it? Thanks

**Comment by S1GSEGV** [comment]
Hi seems just need to add "--without-libiberty --disable-Werror" when doing ./configure

**Comment by dikkedimi** [comment]
here, that leads to:
```
Traceback (most recent call last):
  File "/Users/user/Development/distcc-3.4/./include_server/setup.py", line 34, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'
make: *** [include-server] Error 1

```
