### ISSUE TITLE
Does zeroconf work?

### ISSUE THREAD

**Issue by S1GSEGV** [marksatt/DistCode#14]
I build the distcc/distccd, It works with hosts file contains IP, when I tried "+zeroconf" it failed to distribute to the slave. Just want to know does zeroconf work on mac? Thanks

**Comment by marksatt** [comment]
You shouldn't need to mess with the command-line tools directly if you use the DistCode GUI - on one Mac setup DistCode to run as the coordinator and then have all the other Macs setup to connect their DistCode instance to the coordinator machine.
