### ISSUE TITLE
distcc-read-only fails to build on a fresh checkout

### ISSUE THREAD

**Issue by jtgans** [marksatt/DistCode#3]
make: **\* No rule to make target `config.status', needed by`Makefile'.  Stop.
Command /usr/bin/make failed with exit code 2

**Comment by marksatt** [comment]
Ah, sorry about this. You need to go into the distcc project & ./configure. This shouldn't happen with the new Icecc version of DistCode - WARNING: this rewrite is not complete & does not yet work!
