### ISSUE TITLE
DistCode window expands too wide and positions itself wrongly

### ISSUE THREAD

**Issue by jtgans** [marksatt/DistCode#6]
Occurs on Yosemite.

![screen shot 2015-03-20 at 4 31 54 pm](https://cloud.githubusercontent.com/assets/595205/6762511/ce865c7a-cf1e-11e4-9948-b687145c7853.png)

**Comment by jtgans** [comment]
Logs from Console:

3/20/15 5:16:36.191 PM DistCode[3092]: NSWindow warning: adding an unknown subview: <NSView: 0x61800013de20>
3/20/15 5:16:36.193 PM DistCode[3092]: Call stack:
(
    0   AppKit                              0x00007fff8ecc48fc -[NSThemeFrame addSubview:] + 107
    1   DistCode                            0x0000000100a2fcb2 -[OBMenuBarWindow initialSetup] + 2706
    2   DistCode                            0x0000000100a2f13d -[OBMenuBarWindow initWithContentRect:styleMask:backing:defer:] + 301
    3   AppKit                              0x00007fff8e61a105 -[NSWindowTemplate nibInstantiate] + 567
    4   AppKit                              0x00007fff8e5eee8b -[NSIBObjectData instantiateObject:] + 309
    5   AppKit                              0x00007fff8ead32d1 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 452
    6   AppKit                              0x00007fff8e5e3605 loadNib + 384
    7   AppKit                              0x00007fff8eb545ab +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 313
    8   AppKit                              0x00007fff8e5e2cd5 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
    9   AppKit                              0x00007fff8e5e2aa1 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 344
    10  AppKit                              0x00007fff8e5de549 NSApplicationMain + 605
    11  DistCode                            0x0000000100a43922 main + 34
    12  libdyld.dylib                       0x00007fff8ac5b5c9 start + 1
    13  ???                                 0x0000000000000001 0x0 + 1
)

**Comment by marksatt** [comment]
I've seen this intermittently but never determined the cause - removing all the DistCode plists & caches, especially the saved application state should stop it.

The Yosemite warning is actually harmless & is a natural function of the way OBMenuBarWindow operates. Silencing that is not a priority.

**Comment by marksatt** [comment]
This shouldn't be a problem anymore.
